version: '3.4'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - gem_cache:/usr/local/bundle/gems
    env_file:
      - .env
      - .env.development
      - .env.development.local
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  redis:
    image: redis:5.0.7

  sidekiq:
    image: desbrav-backend-app_dev:latest
    depends_on:
      - dev
      - database
      - redis
    volumes:
      - ./:/app
      - gem_cache:/usr/local/bundle/gems
    env_file:
      - .env
      - .env.development
      - .env.development.local
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
